config/routes.rb
BitcoinExhangeRate::Application.routes.draw do
  resources :trades
  root :to => 'trades#new'

end

app/models/trade.rb
require 'json'
require 'net/http'

class Trade < ActiveRecord::Base
  attr_accessible :btc, :trade_type, :usd, :price
  before_create :validate_trade
  def validate_trade
    # Get Data from MtGox
    r = Net::HTTP.get_response("data.mtgox.com", "/api/1/BTCUSD/depth/fetch")
    asks = JSON.parse(r.body)["return"]["asks"]
    bids = JSON.parse(r.body)["return"]["bids"]
    self.price = nil

    # Is this a buy or a sell?
    if self.trade_type == "buy"
      trades = asks
    else
      # This is a sell not a buy
      trades = bids
    end

    # Are we talking in terms of BTC or dollars?
    if self.usd.nil? # Then we use BTC
      while self.price.nil? and trade = trades.shift
        if self.btc < trade["amount"]
          # We can use this price because there is enough depth
          self.price = trade["price"]
        end
      end
      self.usd = self.btc * price
    else
      # Use USD since we have it
      while self.price.nil? and trade = trades.shift
        if self.usd < trade["amount"]
          # We can use this price because there is enough depth
          self.price = trade["price"]
        end
      end
      self.btc = self.usd /  price
    end
    
    # Account for fee
    if self.trade_type == "buy"
      self.btc = self.btc * 0.99
    else
      self.usd = self.usd * 0.99
    end
  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/trades_controller.rb
class TradesController < ApplicationController
  # GET /trades
  # GET /trades.json
  def index
    @trades = Trade.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @trades }
    end
  end

  # GET /trades/1
  # GET /trades/1.json
  def show
    @trade = Trade.find(params[:id])
    if @trade.trade_type == "buy"
      fee = @trade.btc / 0.99 - @trade.btc
      fee = fee.round(8)
      @fee = "#{fee} BTC"
    else 
      fee = @trade.usd / 0.99 - @trade.usd
      fee = fee.round(2)
      @fee = "$#{fee} USD"
    end

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @trade }
    end
  end

  # GET /trades/new
  # GET /trades/new.json
  def new
    @trade = Trade.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @trade }
    end
  end

  # GET /trades/1/edit
  def edit
    @trade = Trade.find(params[:id])
  end

  # POST /trades
  # POST /trades.json
  def create
    @trade = Trade.new(params[:trade])

    respond_to do |format|
      if @trade.save
        format.html { redirect_to @trade, notice: 'Trade was successfully created.' }
        format.json { render json: @trade, status: :created, location: @trade }
      else
        format.html { render action: "new" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /trades/1
  # PUT /trades/1.json
  def update
    @trade = Trade.find(params[:id])

    respond_to do |format|
      if @trade.update_attributes(params[:trade])
        format.html { redirect_to @trade, notice: 'Trade was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @trade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /trades/1
  # DELETE /trades/1.json
  def destroy
    @trade = Trade.find(params[:id])
    @trade.destroy

    respond_to do |format|
      format.html { redirect_to trades_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/trades_helper.rb
module TradesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Calculate Bitcoin Exchange Rate</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="page-container">

    <div class="container">


<%= yield %>

<br><br>
</div>
</body>
</html>

app/views/trades/_form.html.erb
<%= form_for(@trade) do |f| %>
  <% if @trade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trade.errors.count, "error") %> prohibited this trade from being saved:</h2>

      <ul>
      <% @trade.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.select :trade_type, options_for_select(["buy", "sell"]) %>
  </div>
  <div class="field">
    <%= f.label :usd %>
    <%= f.text_field :usd %>
  </div>
  <div class="field">
    <%= f.label :btc %>
    <%= f.text_field :btc %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trades/edit.html.erb
<h1>Editing trade</h1>

<%= render 'form' %>

<%= link_to 'Show', @trade %> |
<%= link_to 'Back', trades_path %>

app/views/trades/index.html.erb
<h1>Listing trades</h1>

<table>
  <tr>
    <th>Trade type</th>
    <th>Usd</th>
    <th>Btc</th>
    <th>Price</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @trades.each do |trade| %>
  <tr>
    <td><%= trade.trade_type %></td>
    <td><%= trade.usd %></td>
    <td><%= trade.btc %></td>
    <td><%= trade.price %></td>
    <td><%= link_to 'Show', trade %></td>
    <td><%= link_to 'Edit', edit_trade_path(trade) %></td>
    <td><%= link_to 'Destroy', trade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Trade', new_trade_path %>

app/views/trades/new.html.erb
<center>
<div class="trade-box">
  <h1>Calculate Trade</h1>

  <%= render 'form' %>
<small>1% fee will be added to all trades.</small>
</div>
<center>

app/views/trades/show.html.erb
<center>
<div class="trade-box result">
<h2>Trade Calculation</h2>
<p>
  <b>Trade type:</b>
  <%= @trade.trade_type %>
</p>

<p>
  <b>Usd:</b>
  $<%= @trade.usd.round(2) %>
</p>

<p>
  <b>Btc:</b>
  <%= @trade.btc.round(8) %>
</p>

<p>
  <b>Price:</b>
  $<%= @trade.price.round(2) %>
</p>
<p>
  <b>Fee:</b>
  <%= @fee%>
</p>
<p><a href="/">Make another Calculation</a></p>
</div>
</center>